name: test_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^12.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  chat_bubbles: ^1.6.0
  freezed_annotation: ^2.4.1


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.5
  analyzer: ^6.2.0
  go_router_builder: any
  build_verify: any
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
